set(CPACK_PACKAGE_VENDOR "mjpg-streamer")
set(CPACK_PACKAGE_CONTACT "? <?@?>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MJPG-streamer")
set(CPACK_PACKAGE_VERSION_MAJOR 9999)
set(CPACK_PACKAGE_VERSION_MINOR 99)
set(CPACK_PACKAGE_VERSION_PATCH 99)
set(CPACK_GENERATOR "DEB")

include(CPack)
