set(CPACK_PACKAGE_VENDOR "mjpg-streamer")
set(CPACK_PACKAGE_CONTACT "? <?@?>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "MJPG-streamer")
set(CPACK_PACKAGE_VERSION_MAJOR 2015)
set(CPACK_PACKAGE_VERSION_MINOR 8)
set(CPACK_PACKAGE_VERSION_PATCH 5)
set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE armhf)

include(CPack)
